apiVersion: apps/v1
kind: Deployment
metadata:
  name: sorteos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorteos-api
  template:
    metadata:
      labels:
        app: sorteos-api
    spec:
      containers:
        - name: sorteos-api
          image: back-tfg-sorteos-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8003
          env:
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: sorteos_db
          command: ["python", "manage.py", "runserver", "0.0.0.0:8003"]
